### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by elliotwutingfeng** [chingu-voyages/v39-bears-team-14#20]
****Feature Description****
Allow users to sign up and login so they can post comments on the guestbook. This helps to reduce likelihood of spam commetns and allows app administrator to ban users for misconduct. Also, only logged in users can add songs from the soundcloud player to their favourites, and suggest new songs to add to the playlist.

****Major User Stories/tasks****

- [x] **User Story:** As a User, I want to sign up with my email address or Google/Microsoft Account etc.
  - [x] **Task:** Backend user creation with email
  - [ ] **Task:** Backend user creation with Google/Microsoft (optional)
  - [x] **Task:** Draggable sign up form window
  - [x] **Task:** Connect sign up form to backend

- [x] **User Story:** As a User, I want to Log In and Log Out. Mima Kim is responsible?
  - [x] **Task:** Draggable login form (maybe on the same window component as the sign up form (see poolsuite.net signup/login form)
  - [ ] **Task:** Connect login form to backend
  - [x] **Task:** Logout button
  - [x] **Task:** Connect logout button to backend

- [x] **User Story:** As a User, I want to change my password when I am already logged in
  - [x] **Task:** Password change form
  - [ ] **Task:** Connect password change form to backend

- [x] **User Story:** As a User, I want to reset my password using my email address if I forget my password
  - [x] **Task:** Forgot password form
  - [x] **Task:** Connect "forgot password" form to backend

- [ ] **User Story:** As an admin, I want to block or delete any spam user.
  - [ ] **Task:** Backend user email banlist add/update/remove
  - [ ] **Task:** Backend prevent banned user emails from posting comments and from logging in
  - [ ] **Task:** Frontend admin user management page
  - [ ] **Task:** Connect user management page to backend

****Additional Considerations****
