### ISSUE TITLE
Real-time Guestbook

### ISSUE THREAD

**Issue by elliotwutingfeng** [chingu-voyages/v39-bears-team-14#21]
****Feature Description****
Guestbook for users to leave comments, respond to comments by others, and optionally, their twitter handle. This makes the users feel part of the app's community.

****Major User Stories/tasks****

- [ ] **User Story:** As a User, I want to post comments on the guestbook, read comments by others, and optionally share my twitter handle
  - [ ] **Task:** Guestbook window has form fields `Nickname`, `Message`, `@twitter` 
  - [ ] **Task:** Guestbook window has a `Post` button for form submission
  - [ ] **Task:** Guestbook window displays all comments that are not marked as spam
  - [ ] **Task:** Backend stores all comments and handles requests to add comments
  - [ ] **Task:** Integrate guestbook frontend with guestbook backend
- [ ] **User Story:** As an admin, I want to delete spam posts from the guestbook
  - [ ] **Task:** Admin page can view existing comments
  - [ ] **Task:** Admin page can be used to mark comments as spam and archive them (archive & not delete, to keep track of what users have commented)
  - [ ] **Task:** Admin page can un-archive comments marked as spam (i.e. make them visible to users again)

****Additional Considerations****

**Comment by mireu-san** [comment]
I will try building up the first task.
Task: Guestbook window has form fields Nickname, Message, @twitter
