### ISSUE TITLE
SoundCloud Player

### ISSUE THREAD

**Issue by elliotwutingfeng** [chingu-voyages/v39-bears-team-14#22]
****Feature Description****
Music player for users to stream retro 00s songs from soundcloud, for nostalgic immersion.

****Major User Stories/tasks****

- [ ] **User Story:** As an admin, I want to edit or put my favourite retro songs/playlists to let visitor can see my music taste.
  - [ ] **Task:** Admin page for create/update/delete preset playlists/songs
  - [ ] **Task:** Backend to store preset playlists/songs
  - [ ] **Task:** Connect Admin page and music player to backend

- [ ] **User Story:** As a User, I want to play retro music from soundcloud
  - [ ] **Task:** Menu for selecting from range of preset soundcloud playlists
  - [x] **Task:** Playback controls (previous track, play/pause, next track, adjust volume)
  - [x] **Task:** Connect music player interface to invisible soundcloud player widget

- [ ] **User Story:** As a User, I want to suggest new songs from soundcloud (share a link)
  - [ ] **Task:** Pop up window form for suggestion of soundcloud songs
  - [ ] **Task:** Backend to receive and store song suggestions
  - [ ] **Task:** Admin page for viewing song suggestions submitted by users
  - [ ] **Task:** Connect form and admin page to backend

- [x] **User Story:** As a User, I want to add songs I like to my favourites
  - [x] **Task:** Button to add/remove current playing song to/from user's favourites
  - [x] **Task:** Backend to store song into user's favourites
  - [x] **Task:** Connect like/unlike button to backend
(instead, why don't we lead user to see the detail info by leaving redirection link?)

****Additional Considerations****
